import type { Metadata } from 'next';
import { Instrument_Sans, Instrument_Serif } from 'next/font/google';
import Link from 'next/link';
import { ModalProvider } from '@/context/ModalContext';
import ClientFooter from '../components/ClientFooter';
import TitleOverlay from '../components/TitleOverlay';
import './globals.css';

const instrumentSans = Instrument_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

const instrumentSerif = Instrument_Serif({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
  variable: '--font-instrument-serif',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${instrumentSans.className} ${instrumentSerif.variable}`}>
        <ModalProvider>
          <div className="main-container min-h-screen flex flex-col bg-light-gray">
            {/* Header */}
            <header className="py-6 text-center md:h-[200px]">
              <Link href="/" className="text-sm inline-block">
                The design practice<br />of Austen Ezzell
              </Link>
            </header>

            {/* Main Content */}
            <main className="flex-1 flex items-center justify-center">
              {children}
            </main>

            {/* Footer container */}
            <div id="footer-root" />
            <ClientFooter />
            <TitleOverlay />
          </div>
        </ModalProvider>
      </body>
    </html>
  );
}
